### ISSUE TITLE
External File Attachment Not Working

### ISSUE THREAD

**Issue by woswald** [agrc/daq-web-framework#31]
### Steps to reproduce
1. Navigate to http://test.mapserv.utah.gov/daq/
2. Click on a facilities point.
3. Click on EDoc Items tab.
4. Click Choose File next to External File.
5. Choose a PDF file from computer to attach (PM25.pdf). Select the file and click open.
6. Click attach.
7. Error Window pops up see first image.
8. Error Window then change to error, try again?
9. File size: 6,557 kb File format: pdf
10. Tried the same process with a different file (smaller file: PM25_1333km.pdf): Size: 1,620 kb Format: PDF, and the process works correctly.
11. Tried the same process with a different file (larger file: DAQ-2017-002501.pdf): Size: 3.93 mb Format: PDF, and the process works correctly.

### Expected behaviour
Should be able to attach a file to a point using the external file attachment tool. I should get a success message when the file gets attached.

### Actual behaviour
I instead receive an error and an error, try again? message when I try to attach some files.

### Client configuration
Chrome Version 56.0.2924.87

**Operating system:**
Windows 7

[DAQ-2017-002501.pdf](https://github.com/agrc/daq-web-framework/files/811559/DAQ-2017-002501.pdf)
[PM25.pdf](https://github.com/agrc/daq-web-framework/files/811561/PM25.pdf)
[PM25_1333km.pdf](https://github.com/agrc/daq-web-framework/files/811560/PM25_1333km.pdf)

**Comment by steveoh** [comment]
The url for the service to upload is not found

![image](https://cloud.githubusercontent.com/assets/325813/23473217/a05d96ae-fe6c-11e6-937e-8dc7d903d785.png)

**Comment by steveoh** [comment]
this should be fixed in 1.4.1

**Comment by woswald** [comment]
I am still getting this error (see image) when I try to attach the PM25.pdf file from above:
![image](https://cloud.githubusercontent.com/assets/7386943/23516123/8894e906-ff29-11e6-87fa-109c57f7c4ad.png)

**Comment by steveoh** [comment]
please find this request in your dev tools under the network panel
![image](https://cloud.githubusercontent.com/assets/325813/23516348/388a3550-ff2a-11e6-8957-445998990222.png)

and right click to save as har file with content and email it to me please. Hopefully that will help figure out why this isn't working for you.

**Comment by steveoh** [comment]
I was able to reproduce with that file. Let me check the arcgis online file size limitations to make sure that is not what is going on here.
